services:
    core.handler.user:
        class: CoreBundle\Handler\UserHandler
        arguments: ['@service_container', '@doctrine.orm.entity_manager']
    core.handler.timecontrol:
        class: CoreBundle\Handler\TimecontrolHandler
        arguments: ['@service_container', '@doctrine.orm.entity_manager']
    core.handler.game:
        class: CoreBundle\Handler\GameHandler
        arguments: ['@service_container', '@doctrine.orm.entity_manager']
    core.handler.game.call:
        class: CoreBundle\Handler\CallHandler
        arguments: ['@service_container', '@doctrine.orm.entity_manager']
    core.handler.error:
        class: CoreBundle\Handler\ErrorHandler
        arguments: ['@service_container']
    core.handler.security:
        class: CoreBundle\Handler\SecurityHandler
        arguments: ['@service_container']
