services:
    core.request.error:
        class: CoreBundle\Model\Request\RequestError
    core.handler.user:
        class: CoreBundle\Handler\UserHandler
        arguments: ['@doctrine.orm.entity_manager']
        calls:
          - [setContainer, ['@service_container']]
          - [setRequestError, ['@core.request.error']]
    core.handler.game:
        class: CoreBundle\Handler\GameHandler
        arguments: ['@doctrine.orm.entity_manager']
        calls:
          - [setContainer, ['@service_container']]
          - [setRequestError, ['@core.request.error']]
    core.handler.game.call:
        class: CoreBundle\Handler\CallHandler
        arguments: ['@doctrine.orm.entity_manager']
        calls:
          - [setContainer, ['@service_container']]
          - [setRequestError, ['@core.request.error']]
    core.service.error:
        class: CoreBundle\Service\ErrorService
        arguments: ['@service_container']
    core.user.stat:
        class: CoreBundle\Service\UserStatService
        calls:
          - [setContainer, ['@service_container']]
    core.service.security:
        class: CoreBundle\Service\SecurityService
        arguments: ['@service_container']
    core.service.chess:
        class: CoreBundle\Service\ChessService
        calls:
          - [setContainer, ['@service_container']]
    core.service.immortalchessnet:
        class: CoreBundle\Service\ImmortalchessnetService
        calls:
          - [setContainer, ['@service_container']]
    core.service.chess.uci:
        class: CoreBundle\Service\Chess\UciService
