services:
    core.request.error:
        class: CoreBundle\Model\Request\RequestError
    core.handler.user:
        class: CoreBundle\Handler\UserHandler
        arguments: ['@doctrine.orm.entity_manager']
        calls:
          - [setContainer, ['@service_container']]
          - [setRequestError, ['@core.request.error']]
    core.handler.game:
        class: CoreBundle\Handler\GameHandler
        arguments: ['@doctrine.orm.entity_manager']
        calls:
          - [setContainer, ['@service_container']]
          - [setRequestError, ['@core.request.error']]
    core.handler.game.call:
        class: CoreBundle\Handler\CallHandler
        arguments: ['@doctrine.orm.entity_manager']
        calls:
          - [setContainer, ['@service_container']]
          - [setRequestError, ['@core.request.error']]
    core.handler.tournament:
        class: CoreBundle\Handler\TournamentHandler
        arguments: ['@doctrine.orm.entity_manager']
        calls:
          - [setContainer, ['@service_container']]
          - [setRequestError, ['@core.request.error']]
    core.service.error:
        class: CoreBundle\Service\ErrorService
        arguments: ['@service_container']
    core.user.stat:
        class: CoreBundle\Service\UserStatService
        calls:
          - [setContainer, ['@service_container']]
    core.service.security:
        class: CoreBundle\Service\SecurityService
        arguments: ['@service_container']
    core.service.chess:
        class: CoreBundle\Service\ChessService
        calls:
          - [setContainer, ['@service_container']]
    core.service.immortalchessnet:
        class: CoreBundle\Service\ImmortalchessnetService
        calls:
          - [setContainer, ['@service_container']]
    core.service.swiss:
        class: CoreBundle\Service\Tournament\SwissService
        arguments: ['@doctrine.orm.entity_manager']
        calls:
          - [setContainer, ['@service_container']]
    core.service.round_robin:
        class: CoreBundle\Service\Tournament\RoundrobinService
        arguments: ['@doctrine.orm.entity_manager']
        calls:
          - [setContainer, ['@service_container']]
    core.service.draw.factory:
        class: CoreBundle\Service\Tournament\TournamentDrawFactoryService
        arguments: ['@doctrine.orm.entity_manager']
        calls:
          - [setContainer, ['@service_container']]
    core.service.chess.uci:
        class: CoreBundle\Service\Chess\UciService
    core.handler.chat:
        class: CoreBundle\Handler\ChatHandler
        arguments: ['@doctrine.orm.entity_manager']
        calls:
          - [setContainer, ['@service_container']]
          - [setRequestError, ['@core.request.error']]
    core.handler.event:
        class: CoreBundle\Handler\EventHandler
        arguments: ['@doctrine.orm.entity_manager']
        calls:
          - [setContainer, ['@service_container']]
    core.service.event.tournament.create:
        class: CoreBundle\Service\Event\Tournament\CreateTournament
        arguments: ['@doctrine.orm.entity_manager']
        calls:
          - [setContainer, ['@service_container']]
    core.service.playzone_serializer:
        class: CoreBundle\Service\PlayzoneSerializer
        calls:
          - [setContainer, ['@service_container']]