services:
    core.request.error:
        class: CoreBundle\Model\Request\RequestError
    core.handler.user:
        class: CoreBundle\Handler\UserHandler
        arguments: ['@doctrine.orm.entity_manager']
        calls:
          - [setContainer, ['@service_container']]
          - [setRequestError, ['@core.request.error']]
    core.handler.game:
        class: CoreBundle\Handler\GameHandler
        arguments: ['@doctrine.orm.entity_manager']
        calls:
          - [setContainer, ['@service_container']]
          - [setRequestError, ['@core.request.error']]
    core.handler.game.call:
        class: CoreBundle\Handler\CallHandler
        arguments: ['@doctrine.orm.entity_manager']
        calls:
          - [setContainer, ['@service_container']]
          - [setRequestError, ['@core.request.error']]
    core.handler.tournament:
        class: CoreBundle\Handler\TournamentHandler
        arguments: ['@doctrine.orm.entity_manager']
        calls:
          - [setContainer, ['@service_container']]
          - [setRequestError, ['@core.request.error']]
    core.handler.log:
        class: CoreBundle\Handler\LogHandler
        arguments: ['@doctrine.orm.entity_manager']
        calls:
          - [setContainer, ['@service_container']]
          - [setRequestError, ['@core.request.error']]
    core.handler.problem:
        class: CoreBundle\Handler\ProblemHandler
        arguments: ['@doctrine.orm.entity_manager']
        calls:
          - [setContainer, ['@service_container']]
          - [setRequestError, ['@core.request.error']]
    core.service.import_problems:
        class: CoreBundle\Service\Chess\ImportProblemsService
        arguments: ['@doctrine.orm.entity_manager']
        calls:
          - [setContainer, ['@service_container']]
    core.service.error:
        class: CoreBundle\Service\ErrorService
        arguments: ['@service_container']
    core.user.stat:
        class: CoreBundle\Service\UserStatService
        tags:
          - { name: kernel.event_subscriber }
        calls:
          - [setContainer, ['@service_container']]
    core.service.security:
        class: CoreBundle\Service\SecurityService
        arguments: ['@service_container']
    core.service.chess:
        class: CoreBundle\Service\ChessService
        calls:
          - [setContainer, ['@service_container']]
    core.service.chess.game:
        class: CoreBundle\Service\Chess\ChessGameService
    core.service.swiss:
        class: CoreBundle\Service\Tournament\SwissService
        arguments: ['@doctrine.orm.entity_manager']
        calls:
          - [setContainer, ['@service_container']]
    core.service.round_robin:
        class: CoreBundle\Service\Tournament\RoundrobinService
        arguments: ['@doctrine.orm.entity_manager']
        calls:
          - [setContainer, ['@service_container']]
    core.service.draw.factory:
        class: CoreBundle\Service\Tournament\TournamentDrawFactoryService
        arguments: ['@doctrine.orm.entity_manager']
        calls:
          - [setContainer, ['@service_container']]
    core.service.tournament_table.factory:
        class: CoreBundle\Service\Tournament\TournamentTable\TournamentTableFactory
    core.service.chess.uci:
        class: CoreBundle\Service\Chess\UciService
        calls:
          - [setContainer, ['@service_container']]
    core.handler.chat:
        class: CoreBundle\Handler\ChatHandler
        arguments: ['@doctrine.orm.entity_manager']
        calls:
          - [setContainer, ['@service_container']]
          - [setRequestError, ['@core.request.error']]
    core.handler.event:
        class: CoreBundle\Handler\EventHandler
        arguments: ['@doctrine.orm.entity_manager']
        calls:
          - [setContainer, ['@service_container']]
    core.service.event.tournament.create:
        class: CoreBundle\Service\Event\Tournament\CreateTournament
        arguments: ['@doctrine.orm.entity_manager']
        calls:
          - [setContainer, ['@service_container']]
    core.service.playzone_serializer:
        class: CoreBundle\Service\PlayzoneSerializer
        calls:
          - [setContainer, ['@service_container']]
    core.service.date:
        class: CoreBundle\Service\DateService
        calls:
          - [setContainer, ['@service_container']]
    core.user_setting.codes:
        class: CoreBundle\Service\UserSettingService
        calls:
          - [setContainer, ['@service_container']]
    core.service.chess.pgn:
        class: CoreBundle\Service\Chess\PgnService
        tags:
          - { name: kernel.event_subscriber }
        calls:
          - [setContainer, ['@service_container']]
    core.service.rating:
        class: CoreBundle\Service\RatingService
        tags:
          - { name: kernel.event_subscriber }
        calls:
          - [setContainer, ['@service_container']]