services:
    core.handler.user:
        class: CoreBundle\Handler\UserHandler
        arguments: ['@service_container', '@doctrine.orm.entity_manager']
    core.handler.timecontrol:
        class: CoreBundle\Handler\TimecontrolHandler
        arguments: ['@service_container', '@doctrine.orm.entity_manager']
    core.handler.game:
        class: CoreBundle\Handler\GameHandler
        arguments: ['@service_container', '@doctrine.orm.entity_manager']
    core.handler.game.call:
        class: CoreBundle\Handler\CallHandler
        arguments: ['@service_container', '@doctrine.orm.entity_manager']
    core.service.error:
        class: CoreBundle\Service\ErrorService
        arguments: ['@service_container']
    core.service.security:
        class: CoreBundle\Service\SecurityService
        arguments: ['@service_container']
