services:
    ws.handler.client.message:
        class: WebsocketServerBundle\Handler\ClientMessageHandler
        arguments: ['@service_container']
    ws.service.signaling.client_message_factory:
        class: WebsocketServerBundle\Service\Signaling\ClientMessageFactory
        calls:
            - [setContainer, ['@service_container']]
    ws.service.signaling.server_game:
        class: WebsocketServerBundle\Service\Signaling\Server\GameSignalerServer
        calls:
            - [setContainer, ['@service_container']]
    ws.service.event.tournament.start_round:
        class: WebsocketServerBundle\Service\Event\Tournament\StartTournamentRound
        calls:
            - [setContainer, ['@service_container']]
    ws.playzone.server:
        class: WebsocketServerBundle\Service\PlayzoneServer
        arguments: ['@logger']
        tags:
            - { name: monolog.logger, channel: ws }
    ws.playzone.client:
        class: WebsocketServerBundle\Service\PlayzoneClient
        arguments: ['%app_core_websocket_server%']
    ws.playzone.client.sender:
        class: WebsocketServerBundle\Service\Client\PlayzoneClientSender
        calls:
            - [setContainer, ['@service_container']]
    ws.playzone.bot:
        class: WebsocketServerBundle\Service\Bot\Bot
        calls:
            - [setContainer, ['@service_container']]