user_api:
    resource: "@ApiBundle/Controller/UserController.php"
    type:     rest
    prefix:   /
    defaults: {_format: json}

timecontrol_api:
    resource: "@ApiBundle/Controller/TimecontrolController.php"
    type:     rest
    prefix:   /
    defaults: {_format: json}

game_api:
    resource: "@ApiBundle/Controller/GameController.php"
    type:     rest
    prefix:   /
    defaults: {_format: json}

call_api:
    resource: "@ApiBundle/Controller/CallController.php"
    type:     rest
    prefix:   /
    defaults: {_format: json}

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

