<?php

namespace ImmortalchessNetBundle\Repository;

use Doctrine\ORM\EntityRepository;
use ImmortalchessNetBundle\Entity\Forum;
use ImmortalchessNetBundle\Exception\Forum\ForumNotFoundException;

/**
 * ForumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForumRepository extends EntityRepository
{
    /**
     * Finds an entity by its primary key / identifier.
     *
     * @param mixed $id The identifier.
     * @param int|null $lockMode One of the \Doctrine\DBAL\LockMode::* constants
     *                              or NULL if no specific lock mode should be used
     *                              during the search.
     * @param int|null $lockVersion The lock version.
     *
     * @return Forum
     * @throws ForumNotFoundException
     */
    public function find($id, $lockMode = null, $lockVersion = null) : Forum
    {
        $forum = parent::find($id, $lockMode, $lockVersion);

        if (!$forum instanceof Forum) {
            throw new ForumNotFoundException;
        }

        return $forum;
    }

}
