<?php

namespace ImmortalchessNetBundle\Repository;

use CoreBundle\Exception\Handler\User\UserNotFoundException;
use Doctrine\ORM\EntityRepository;
use ImmortalchessNetBundle\Entity\ImmortalUser;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImmortalUserRepository extends EntityRepository
{
    /**
     * @param string $userName
     * @return ImmortalUser
     */
    public function findOneByUsername(string $userName) : ImmortalUser
    {
        $user = parent::findOneByUsername($userName);

        if (!$user instanceof ImmortalUser) {
            throw new UserNotFoundException;
        }

        return $user;
    }
    
    /**
     * @param string $email
     * @return ImmortalUser
     */
    public function findOneByEmail(string $email) : ImmortalUser
    {
        $user = parent::findOneByEmail($email);

        if (!$user instanceof ImmortalUser) {
            throw new UserNotFoundException;
        }

        return $user;
    }
}
