<?php

namespace ImmortalchessNetBundle\Repository;

use Doctrine\ORM\EntityRepository;
use ImmortalchessNetBundle\Entity\Thread;
use ImmortalchessNetBundle\Exception\Thread\ThreadNotFoundException;

/**
 * ThreadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThreadRepository extends EntityRepository
{
    /**
     * Finds an entity by its primary key / identifier.
     *
     * @param mixed $id The identifier.
     * @param int|null $lockMode One of the \Doctrine\DBAL\LockMode::* constants
     *                              or NULL if no specific lock mode should be used
     *                              during the search.
     * @param int|null $lockVersion The lock version.
     *
     * @return Thread
     * @throws ThreadNotFoundException
     */
    public function find($id, $lockMode = null, $lockVersion = null) : Thread
    {
        $thread = parent::find($id, $lockMode, $lockVersion);
        
        if (!$thread instanceof Thread) {
            throw new ThreadNotFoundException;
        }

        return $thread;
    }

}
