services:
  ws.playzone.client:
      class: WebsocketClientBundle\Service\PlayzoneClient
      arguments: ['%app_core_websocket_server%']
  ws.playzone.client.sender:
      class: WebsocketClientBundle\Service\Client\PlayzoneClientSender
      calls:
          - [setContainer, ['@service_container']]
  ws.playzone.shutdown_server:
      class: WebsocketClientBundle\Service\ShutdownServerService
      arguments:
        - '@ws.playzone.client.sender'
      tags:
        - { name: kernel.event_subscriber }
