<?php

namespace CoreBundle\Repository;

use CoreBundle\Entity\Event;
use CoreBundle\Entity\User;
use CoreBundle\Exception\Handler\Event\EventNotFoundException;
use Doctrine\ORM\EntityRepository;

/**
 * GameMoveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * 
 * @method Event[] findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
 */
class EventRepository extends EntityRepository
{
    /**
     * Finds an entity by its primary key / identifier.
     *
     * @param mixed $id The identifier.
     * @param int|null $lockMode One of the \Doctrine\DBAL\LockMode::* constants
     *                              or NULL if no specific lock mode should be used
     *                              during the search.
     * @param int|null $lockVersion The lock version.
     *
     * @return Event
     * @throws EventNotFoundException
     */
    public function find($id, $lockMode = null, $lockVersion = null) : Event
    {
        $event = parent::find($id, $lockMode, $lockVersion);
        
        if (!$event instanceof Event) {
            throw new EventNotFoundException;
        }

        return $event;
    }

}
