<?php

namespace CoreBundle\Repository;

use CoreBundle\Entity\User;

/**
 * GameMoveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameMoveRepository extends \Doctrine\ORM\EntityRepository
{
    
}
