<?php

namespace CoreBundle\Repository;

use CoreBundle\Entity\User;

/**
 * GameCallRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameCallRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param User $user
     * @param $fieldForUser
     * @return \CoreBundle\Entity\GameCall[]
     */
    public function findByUser(User $user, $fieldForUser)
    {
        return $this->findBy([$fieldForUser => $user]);
    }
}
