<?php

namespace CoreBundle\Repository;

/**
 * TimecontrolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimecontrolRepository extends \Doctrine\ORM\EntityRepository
{
}
