<?php

namespace CoreBundle\Repository;

use CoreBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @method User findOneByLogin(string $login)
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
}
