<?php

namespace CoreBundle\Repository;

use CoreBundle\Entity\User;
use CoreBundle\Exception\Handler\User\UserNotFoundException;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param string $login
     * @return User
     * @throws UserNotFoundException
     */
    public function findOneByLogin(string $login) : User
    {
        $user = parent::findOneBy(['login' => $login]);

        if (!$user instanceof User) {
            throw new UserNotFoundException;
        }

        return $user;
    }

    /**
     * @param string $email
     * @return User
     * @throws UserNotFoundException
     */
    public function findOneByEmail(string $email) : User
    {
        $user = parent::findOneBy(['email' => $email]);

        if (!$user instanceof User) {
            throw new UserNotFoundException;
        }

        return $user;
    }
}
