services:
  immortalchessnet.service.immortalchessnet:
    class: ImmortalchessNetBundle\Service\ImmortalchessnetService
    calls:
      - [setContainer, ['@service_container']]
  immortalchessnet.service.publish:
    class: ImmortalchessNetBundle\Service\PublishService
    calls:
      - [setContainer, ['@service_container']]
  immortalchessnet.service.user:
    class: ImmortalchessNetBundle\Service\ImmortalUserService
    calls:
      - [setContainer, ['@service_container']]