services:
  immortalchessnet.service.immortalchessnet:
    class: ImmortalchessNetBundle\Service\ImmortalchessnetService
    calls:
      - [setContainer, ['@service_container']]
  immortalchessnet.service.publish:
    class: ImmortalchessNetBundle\Service\PublishService
    calls:
      - [setContainer, ['@service_container']]
  immortalchessnet.service.user:
    class: ImmortalchessNetBundle\Service\ImmortalUserService
    calls:
      - [setContainer, ['@service_container']]
  immortalchessnet.service.event.post_problem:
    class: ImmortalchessNetBundle\Service\Event\PostProblemService
    calls:
      - [setContainer, ['@service_container']]
  immortalchessnet.service.event.new_tournament_notifier:
    class: ImmortalchessNetBundle\Service\Event\NewTournamentNotifierService
    calls:
      - [setContainer, ['@service_container']]
  immortalchessnet.service.text.converter:
    class: ImmortalchessNetBundle\Service\TextConverter
    calls:
      - [setContainer, ['@service_container']]
  immortalchess.service.database_converter:
    class: ImmortalchessNetBundle\Service\DatabaseConverter
    arguments:
      - '@immortalchessnet.service.text.converter'
      - '%app_immortalchess.database_host%'
      - '%app_immortalchess.database_user%'
      - '%app_immortalchess.database_password%'
      - '%app_immortalchess.database_name%'
      - '@doctrine'
      - '@filesystem'
